[project]
name = "diquark-simulations"
version = "0.1.0"
description = "Simulated data generation scripts for the ultraheavy diquark studies."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "madgraph-script-generator",
    "matplotlib>=3.11.1",
    "numpy>=2.5.2",
    "pandas>=3.0.5",
    "typer>=0.27.1",
]

[build-system]
requires = ["uv_build>=0.12.5,<0.13"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "ultraheavy_diquark"

[tool.uv.sources]
madgraph-script-generator = { git = "https://github.com/IFIN-DFPE/madgraph-script-generator" }

[tool.ruff]
exclude = [".venv", "scripts/diquarkVquark2023_UFO"]

[tool.ruff.lint]
ignore = [
    # Don't reorder/organize imports
    "I001",
]
